@host=http://localhost:5085
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZDM2ZTMzMy1iNjkwLTRiZmQtOWVjYi0yOTE2YWI5NTZlODciLCJnaXZlbl9uYW1lIjoiRnJhbmNvIiwiZmFtaWx5X25hbWUiOiJGaWxpcHBpIiwianRpIjoiNGRhYjQxM2QtNDMyOS00N2NiLWExNjktYzAwZDViYjljMmViIiwiZXhwIjoxNjk4MDgxMjM2LCJpc3MiOiJXb3JrT3JkZXJNYW5hZ2VyIiwiYXVkIjoiV29ya09yZGVyTWFuYWdlciJ9.jsGyUnqbLzdBKK-Auugi0_8UL4FA73Z97dy_9388VOQ

POST {{host}}/Order/New
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Franco",
  "lastName": "Filippi",
  "lines": [
    {
      "name": "line 1",
      "description": "desc 1"
    },
    {
      "name": "line 2",
      "description": "desc 2"
    }
  ]
}