@host=http://localhost:5085
@orderId=5471a4c8-41f6-486c-b8fa-7693f005cd22
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGZjMGE1Ny0zNmQ5LTRmYzctODIxZS1iYzkyMzlhYzcyNjgiLCJnaXZlbl9uYW1lIjoiRnJhbmNvIiwiZmFtaWx5X25hbWUiOiJGaWxpcHBpIiwianRpIjoiOTNlZTIwMjgtNWRhMS00ZDhhLTgxNGEtZTFjZWU2OTdiNDk3IiwiZXhwIjoxNjk3NzMxMzE1LCJpc3MiOiJXb3JrT3JkZXJNYW5hZ2VyIiwiYXVkIjoiV29ya09yZGVyTWFuYWdlciJ9.bB0yA6O6LBBzZt-TGUVOqvgHRjz3kjWmAD742XRPOZw


GET {{host}}/Order/GetOrderById/?Id={{orderId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
}