version: '3'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: workordermanager
      POSTGRES_USER: workorderapp
      POSTGRES_PASSWORD: Tester123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: my-adminer
    ports:
      - "8080:8080"
