@host=http://localhost:5085
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjlkOTYxNC0yYmU4LTQ4OTUtOTQxMi03ZTIwNTA4M2FiZmUiLCJnaXZlbl9uYW1lIjoiRnJhbmNvIiwiZmFtaWx5X25hbWUiOiJGaWxpcHBpIiwianRpIjoiZWZiZDdiYzYtODk5Ni00NzdlLWE5MTktYjgyYmYwNWQzNjVmIiwiZXhwIjoxNjk3ODE0ODk5LCJpc3MiOiJXb3JrT3JkZXJNYW5hZ2VyIiwiYXVkIjoiV29ya09yZGVyTWFuYWdlciJ9.SHqNlpL6-tqjphE-kZriXPWgJHs4-6IZY8gSQp2dnNY

POST {{host}}/Order/New
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Franco",
  "lastName": "Filippi",
  "lines": [
    {
      "name": "line 1",
      "description": "desc 1"
    },
    {
      "name": "line 2",
      "description": "desc 2"
    }
  ]
}