@host=http://localhost:5085
@orderId=0f9baf83-d995-4667-a03b-7dd6ed39b96c
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxODc2MWE0NC0xYzVkLTRiZDktYWM4Ni1jNmMyNTcxZDY0ZDQiLCJnaXZlbl9uYW1lIjoiRnJhbmNvIiwiZmFtaWx5X25hbWUiOiJGaWxpcHBpIiwianRpIjoiYmE0NjgxMzEtZWFlZi00MTE4LTk1ZDQtZDkxNDhkZWVhYmIzIiwiZXhwIjoxNjk3NjUzMTI3LCJpc3MiOiJXb3JrT3JkZXJNYW5hZ2VyIiwiYXVkIjoiV29ya09yZGVyTWFuYWdlciJ9.vVCSeGroOmxekAsMd6I5mBgQZG5E5ZYEqYabjVkZN9g


GET {{host}}/Order/GetOrderById/?Id={{orderId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
}